"" ----------------------------
"" --- plugins declarations ---
"" ----------------------------

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" plugins for code autocompletion, language servers and the like
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'zchee/deoplete-jedi'
Plug 'shougo/neco-vim'
Plug 'davidhalter/jedi-vim', { 'for':  'python' }
Plug 'vim-scripts/AutoComplPop'
Plug 'dense-analysis/ale'

" git integration in vim
Plug 'tpope/vim-fugitive'
Plug 'oguzbilgic/vim-gdiff'
Plug 'stsewd/fzf-checkout.vim'
Plug 'airblade/vim-gitgutter'

" file navigation
Plug 'francoiscabrol/ranger.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" vim decorations and looks
Plug 'machakann/vim-highlightedyank'
Plug 'frazrepo/vim-rainbow'
Plug 'thaerkh/vim-indentguides'
Plug 'mhinz/vim-startify'
Plug 'mechatroner/rainbow_csv'
Plug 'tpope/vim-sensible'
Plug 'itchyny/lightline.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'lifepillar/vim-solarized8'

" settings that make vim easier to use
Plug 'ervandew/supertab'
Plug 'yuttie/comfortable-motion.vim'
Plug 'wincent/terminus'
Plug 'haya14busa/is.vim'

" snippets and language specific plugins
Plug 'lervag/vimtex'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

"" ------------------------------------
"" basic settings for colour and themes
"" ------------------------------------

filetype plugin indent on
syntax enable
set termguicolors
set background=dark
colorscheme solarized8

" cursorline and windows frame
set number relativenumber
set wrap
autocmd FileType * set formatoptions-=cro
set ruler
set cursorline
set laststatus=2
set splitbelow splitright
set scrolloff=8

" standard vim behaviour
set noswapfile
set nocompatible
set hidden
set mouse=a
set updatetime=100
set showcmd
set sidescroll=1
set clipboard+=unnamed
set autoindent noexpandtab tabstop=4 shiftwidth=4

" search options
set wildmenu
set hlsearch
set showmatch

" autocompletion options
set shortmess+=c
set completeopt="menuone,preview"
set wildmode=longest,full,list

"" -----------------------------
"" --- automatically loading ---
"" -----------------------------
"" ~/.vim/plugin/mappings.vim
"" ~/.vim/plugin/options.vim
"" -----------------------------

