vim.g.vimtex_view_general_viewer = "zathura"
vim.g.vimtex_view_zathura_options = "-reuse-instance"
vim.g.vimtex_imaps_leader = ","
vim.g.tex_conceal = ""
vim.g.tex_fast = ""
vim.g.tex_flavor = "latex"
